# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [3]:
tf.random.set_seed(42)

In [4]:
from tensorflow.python import keras

In [5]:
import numpy as np
import pandas as pd
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.python.keras.layers.core import Dense,Dropout,Activation,Flatten
#from keras.layers.convolutional import Conv2D,MaxPooling2D
from tensorflow.python.keras.utils import np_utils
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [6]:
from sklearn import datasets
iris = datasets.load_iris()


## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [7]:
# Create feature matrix
X = iris.data

# Create target vector
y = iris.target

# View the first observation's feature values
X[0]

array([5.1, 3.5, 1.4, 0.2])

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [8]:
# Import `train_test_split` from `sklearn.model_selection`
from sklearn.model_selection import train_test_split

# Split the data up in train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [9]:
X_train[:5]

array([[5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5]])

In [10]:
y_train[:5]

array([0, 0, 2, 1, 1])

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [11]:
y_train=tf.keras.utils.to_categorical(
    y_train,
    num_classes=None,
    dtype='float32'
)

y_test=tf.keras.utils.to_categorical(
    y_test,
    num_classes=None,
    dtype='float32'
)


In [12]:
y_train.shape

(112, 3)

In [13]:
y_train[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [14]:
y_test.shape

(38, 3)

In [15]:
y_test[:5]

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [16]:
from tensorflow.keras import layers

model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [17]:
# Add an input layer 
model.add(Dense(4, activation='relu', input_shape=(4,)))

# Add one hidden layer 
model.add(Dense(4, activation='relu'))

# Add an output layer 
model.add(Dense(3, activation='softmax'))

In [18]:
# model.summary()

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [19]:
model.compile(loss='categorical_crossentropy',
              optimizer='SGD',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.layers

In [22]:
model.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.28502995, -0.10217923, -0.25481498, -0.06151801],
        [-0.8077238 ,  0.31986195,  0.41589564,  0.6450928 ],
        [-0.47401667, -0.47943708, -0.32841748,  0.38509697],
        [-0.6353384 ,  0.08324909,  0.12922621,  0.6922721 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.32543713, -0.02688342,  0.7465041 , -0.42922467],
        [ 0.40037042,  0.67994815,  0.77379066,  0.4318593 ],
        [-0.26109576,  0.08172262, -0.41291407,  0.3418085 ],
        [-0.6588274 ,  0.0603506 ,  0.3722121 ,  0.6495498 ]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.44692636,  0.23802137, -0.89363   

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [23]:
# Train neural network
model.fit(X_train, # Features
            y_train, # Target
            epochs=100, # Number of epochs
            verbose=1, # print description after each epoch
            batch_size=1, # Number of observations per batch
            validation_data=(X_test, y_test)) # Data for evaluation

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 9ms/sample - loss: 1.1222 - accuracy: 0.3304 - val_loss: 1.0614 - val_accuracy: 0.3158
Epoch 2/100
112/112 [==============================] - 0s 2ms/sample - loss: 1.0290 - accuracy: 0.3393 - val_loss: 0.9657 - val_accuracy: 0.5526
Epoch 3/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.9084 - accuracy: 0.6071 - val_loss: 0.8325 - val_accuracy: 0.7105
Epoch 4/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.7982 - accuracy: 0.6696 - val_loss: 0.7366 - val_accuracy: 0.7105
Epoch 5/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.7239 - accuracy: 0.6786 - val_loss: 0.6766 - val_accuracy: 0.8158
Epoch 6/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.6739 - accuracy: 0.7321 - val_loss: 0.6193 - val_accuracy: 0.7105
Epoch 7/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.6271 -

Epoch 57/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.2086 - accuracy: 0.9107 - val_loss: 0.0946 - val_accuracy: 1.0000
Epoch 58/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1962 - accuracy: 0.9286 - val_loss: 0.1356 - val_accuracy: 0.9737
Epoch 59/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1515 - accuracy: 0.9554 - val_loss: 0.1994 - val_accuracy: 0.8684
Epoch 60/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.2185 - accuracy: 0.9286 - val_loss: 0.1048 - val_accuracy: 0.9737
Epoch 61/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.2034 - accuracy: 0.9286 - val_loss: 0.0910 - val_accuracy: 1.0000
Epoch 62/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.2350 - accuracy: 0.9375 - val_loss: 0.7153 - val_accuracy: 0.7105
Epoch 63/100
112/112 [==============================] - 0s 2ms/sample - loss: 0.1911 - accuracy: 0.9286 - val_loss: 0.0850 -

## Question 10

### Make predictions
- Predict labels on one row

In [24]:
score=model.evaluate(X_test,y_test)

38/1 [==================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [25]:
score

[0.07413299440553314, 0.9736842]

In [26]:
y_predict = model.predict(X_test)

In [27]:
# model.predict(X_test[0:1])
y_predict[2]

array([1.3826906e-27, 2.0175078e-06, 9.9999797e-01], dtype=float32)

In [28]:
np.argmax(y_predict[2])

2

#### both predicted and acutal class for test sample checked are same

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [29]:
y_test[2]

array([0., 0., 1.], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [30]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [31]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [32]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [33]:
# run this cell to upload file if you are using google colab
# from google.colab import files
# files.upload()

In [34]:
import numpy as np
import pandas as pd

# read the file
dfs=pd.read_csv("prices.csv")

In [35]:
# check for data upload
dfs.head()

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

In [36]:
# check data type
dfs.dtypes

date       object
symbol     object
open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

In [37]:
#Check shape
dfs.shape

(851264, 7)

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [38]:
# drop columns
dfs.drop(['date','symbol'], axis=1,inplace=True)

In [39]:
# After dropping columns
dfs.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data

- This step is done to make the execution faster

In [40]:
# Taking only first 1000 rows from the data
dfs_1k=dfs[:1000]

In [41]:
dfs_1k.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [42]:
# First 4 columns are features
X = dfs_1k.iloc[:,0:4]
X.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [43]:
# 'volume' column is label
y_actual=dfs_1k['volume']
y_actual.head() 

0    2163600.0
1    2386400.0
2    2489500.0
3    2006300.0
4    1408600.0
Name: volume, dtype: float64

In [44]:
# Normalizing label column by dividing it with 1,000,000
y_actual/=1000000
y_actual.head()

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [45]:
# Converting features to numpy array with dtype=float32
X=X.astype('float32').to_numpy()

In [46]:
# check shape of feature
X.shape

(1000, 4)

In [47]:
# check data dtype
X.dtype

dtype('float32')

In [48]:
X[:5]

array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       [115.48, 116.62, 113.5 , 117.44],
       [117.01, 114.97, 114.09, 117.33]], dtype=float32)

In [49]:
# Converting label to numpy array with dtype=float32
y_actual=y_actual.astype('float32').to_numpy()

In [50]:
y_actual.shape

(1000,)

In [51]:
y_actual[:5]

array([2.1636, 2.3864, 2.4895, 2.0063, 1.4086], dtype=float32)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [52]:
# normalize feature columns

X=tf.math.l2_normalize(
    X,
    axis=None,
    epsilon=1e-12,
    name=None
)

In [53]:
# check normalized data
X

<tf.Tensor: id=46730, shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [54]:
#Initialize Weights and Bias with zeros
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]), name="Bias")

In [55]:
#check for initialization and weigths
print("W:", W)
print("b:", b)

W: <tf.Variable 'Weights:0' shape=(4, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>
b: <tf.Variable 'Bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [56]:
# define function for label prediction

@tf.function 
def prediction(X, W, b):     
    y_pred = tf.add(tf.matmul(X,W),b,name='output')     
    return y_pred 

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [57]:
# define function for loss calculation

@tf.function 
def loss(y_actual, y_pred):     
#     diff = y_actual - y_pred     
#     sqr = tf.square(diff)     
#     avg = tf.reduce_mean(sqr) 
    loss = tf.reduce_mean(tf.square(y_actual-y_pred),name='Loss')
    return loss 

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [58]:
# define  a function for training
def train(x, y_actual, w, b, learning_rate=0.01):          
    # Record mathematical operations on 'tape' to calculate loss     
    with tf.GradientTape() as tape:         
        tape.watch([w,b])         
        current_prediction = prediction(x, w, b)         
        current_loss = loss(y_actual, current_prediction)          
        # Calculate Gradients for Loss with respect to Weights and Bias     
    dw, db = tape.gradient(current_loss,[w, b])          
    # Update Weights and Bias     
    w = w - learning_rate * dw     
    b = b - learning_rate * db          
    return w, b 

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [59]:
# Train the model for 100 epochs using for loop

for i in range(100):         
    W, b = train(X, y_actual, W, b, learning_rate=0.01)     
    print('Current Training Loss on iteration', i, loss(y_actual, prediction(X, W, b)).numpy())

Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11783
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32585
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67299
Current Training Loss on iteration 9 227.89539
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74234
Current Training Loss on iteration 13 225.0808
Current Training Loss on iteration 14 224.44554
Current Training Loss on iteration 15 223.83499
Current Training Loss on iteration 16 223.24931
Current Training Loss on iteration 17 222.68657
Current Training Loss on iteration 18 222.14594
Current Training Loss on iteration 19 221.62688
Current Training Loss on iteration 20 221.12842
Cur

### Observe values of Weight
- Print the updated values

In [60]:
# The updated weight values
print(f'W : {W.numpy()}')

W : [[0.05478281]
 [0.05488191]
 [0.05422735]
 [0.05533117]]


### Observe values of Bias

- Print the updated values

In [61]:
# updated bias values
print(f'b  = {b.numpy()} ')

b  = [4.607657] 
