# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [1]:
# Importing required packages
import numpy as np
from scipy.stats import ttest_1samp, ttest_ind,mannwhitneyu,levene,shapiro,wilcoxon,f_oneway,chi2_contingency,zscore
import scipy.stats as stats
from statsmodels.stats.power import ttest_power
import matplotlib.pyplot as plt

In [2]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [3]:
t_statistic, p_value = ttest_1samp(GPU1,0)
print("t_statistic = %6.4f \np_value = %6.4e"%(t_statistic, p_value))

t_statistic = 34.0562 
p_value = 7.2289e-15


In [4]:
print("Since p_value=%6.4e is smaller than 0.05, we reject the Null Hypothesis that mean is equal to zero"%p_value)

Since p_value=7.2289e-15 is smaller than 0.05, we reject the Null Hypothesis that mean is equal to zero


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [5]:
t_statistic, p_value = ttest_ind(GPU1, GPU2,equal_var='True')
print("t_statistic = %6.4f \np_value = %6.4f"%(t_statistic, p_value))

t_statistic = -2.6276 
p_value = 0.0138


In [6]:
print("Since ",p_value,"is smaller than 0.05, we reject the Null Hypothesis. \nAnd we can conclude, there is a significant difference between data sets GPU1 & GPU2")

Since  0.013794282041452725 is smaller than 0.05, we reject the Null Hypothesis. 
And we can conclude, there is a significant difference between data sets GPU1 & GPU2


## Question 3

He is trying a third GPU - GPU3.

In [7]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [8]:
t_statistic, p_value = ttest_ind(GPU1, GPU3)
print("t_statistic = %6.4f \np_value = %6.4f"%(t_statistic, p_value))

t_statistic = -1.4989 
p_value = 0.1451


In [9]:
print("Since ",p_value,"is more than 0.05, we can't reject the null hypothesis at 5% level of significance. \nAnd it is evident, there is no significant difference between data sets GPU1 & GPU3")

Since  0.14509210993138993 is more than 0.05, we can't reject the null hypothesis at 5% level of significance. 
And it is evident, there is no significant difference between data sets GPU1 & GPU3


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [10]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [11]:
t_statistic, p_value = levene(e1,e2,e3)
print("t_statistic = %6.4f \np_value = %6.4f"%(t_statistic, p_value))

t_statistic = 2.6742 
p_value = 0.1226


In [12]:
print("Since pvalue is greater than 0.05 (in levene's test), equality of variances is satisfied")

Since pvalue is greater than 0.05 (in levene's test), equality of variances is satisfied


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [13]:
t_statistic,P_value=f_oneway(e1,e2,e3) # Directly calling f_oneway function as I have imported it in 1st step
print("t_statistic = %6.4f \np_value = %6.4f"%(t_statistic, p_value))
print('''Statistically significanct evidence is not available to reject null hypothesis at 5% level of significance.
Hence we can conclude that the results for all three experiments are not significantly different.''')

t_statistic = 2.5136 
p_value = 0.1226
Statistically significanct evidence is not available to reject null hypothesis at 5% level of significance.
Hence we can conclude that the results for all three experiments are not significantly different.


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

Type I : Rejecting the null hypothesis when it is true is called Type 1 error. Type I error is represented by alpha level.

Type II : Accepting the null hypothesis when it is false is called Type 2 error.

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


𝐻0 : 𝜇 = 4.5
𝐻𝐴: 𝜇 != 4.5

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [14]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [15]:
chi_sq_Stat, p_value, deg_freedom, exp_freq = chi2_contingency(dice)

print("chi2 stat = %6.4f \np_value = %6.4f \ndegree of freedom = %d "%(chi_sq_Stat, p_value,deg_freedom))

print('Contigency Table\n',exp_freq)

chi2 stat = 23.3157 
p_value = 0.0777 
degree of freedom = 15 
Contigency Table
 [[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [16]:
Z_score=zscore(dice)
print('Z_score :\n',Z_score)

Z_score :
 [[-0.46291005 -0.18884739 -1.83711731  1.44115338]
 [ 1.38873015 -0.64208114  1.22474487  0.        ]
 [ 0.9258201   0.7176201   0.61237244 -1.44115338]
 [-0.9258201   1.62408759  0.61237244 -0.96076892]
 [-1.38873015  0.03776948  0.          0.        ]
 [ 0.46291005 -1.54854863 -0.61237244  0.96076892]]


In [17]:
Z_score=zscore(dice, axis=None, ddof=1) # using n-1 degrees of freedom (ddof=1)
print('Z_score :\n',Z_score)

Z_score :
 [[-0.45530567  0.48132314 -1.07972488  0.48132314]
 [ 0.79353274 -0.14309607  0.48132314 -0.45530567]
 [ 0.48132314  1.73016155  0.16911354 -1.39193448]
 [-0.76751528  2.97899997  0.16911354 -1.07972488]
 [-1.07972488  0.79353274 -0.14309607 -0.45530567]
 [ 0.16911354 -1.39193448 -0.45530567  0.16911354]]


In [18]:
print("Mean of Z_score = ",np.mean(Z_score))

Mean of Z_score =  8.326672684688674e-17


In [19]:
p_values=stats.norm.sf(abs(Z_score),loc=0,scale=1)*2
print('p_values :\n',p_values)

p_values :
 [[0.64888935 0.63028685 0.28026471 0.63028685]
 [0.4274675  0.88621431 0.63028685 0.64888935]
 [0.63028685 0.08360142 0.86570734 0.16394224]
 [0.44277521 0.00289191 0.86570734 0.28026471]
 [0.28026471 0.4274675  0.88621431 0.64888935]
 [0.86570734 0.16394224 0.64888935 0.86570734]]


In [20]:
print('Mean of array of p_values is %5.4f'%np.mean(p_values))

Mean of array of p_values is 0.5377


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [21]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [22]:
t_statistic,P_value=stats.ttest_rel(before,after)
print("T_stats :%5.3f\nP_value :%10.10f"%(t_statistic,P_value))

T_stats :6.043
P_value :0.0000000030


In [23]:
print("Since P_value is less than 0.05, We conclude that weight-loss drug has a significant effect on the weigth of the group")

Since P_value is less than 0.05, We conclude that weight-loss drug has a significant effect on the weigth of the group
